-- Product table reset for Knits by Muna.
-- Run this in Supabase SQL Editor when product inserts fail with ID/FK type errors.
-- This deletes existing product/product-image/inquiry rows and recreates the product schema cleanly.

DROP TABLE IF EXISTS product_images CASCADE;
DROP TABLE IF EXISTS inquiries CASCADE;
DROP TABLE IF EXISTS products CASCADE;

CREATE TABLE IF NOT EXISTS categories (
  id text PRIMARY KEY,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  image_url text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

CREATE TABLE products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL,
  price numeric(10, 2) NOT NULL,
  discounted_price numeric(10, 2),
  image_url text NOT NULL,
  category_id text REFERENCES categories(id),
  in_stock boolean NOT NULL DEFAULT true,
  is_featured boolean NOT NULL DEFAULT false,
  is_new_arrival boolean NOT NULL DEFAULT false,
  is_trending boolean NOT NULL DEFAULT false,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

CREATE TABLE product_images (
  id text PRIMARY KEY,
  product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  image_url text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT now()
);

CREATE TABLE inquiries (
  id text PRIMARY KEY,
  customer_name text NOT NULL,
  customer_phone text,
  message text NOT NULL,
  product_id integer REFERENCES products(id),
  status text NOT NULL DEFAULT 'new',
  created_at timestamp NOT NULL DEFAULT now()
);
