-- One-time repair script for projects that previously created products.id as text.
-- Run in Supabase SQL Editor before using the admin panel.

DO $$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_schema = 'public'
			AND table_name = 'products'
			AND column_name = 'id'
			AND data_type IN ('text', 'character varying')
	) THEN
		ALTER TABLE IF EXISTS product_images DROP CONSTRAINT IF EXISTS product_images_product_id_fkey;
		ALTER TABLE IF EXISTS inquiries DROP CONSTRAINT IF EXISTS inquiries_product_id_fkey;

		-- Start fresh IDs with integer/identity. Safe for empty or test data.
		ALTER TABLE products RENAME COLUMN id TO old_id;
		ALTER TABLE products ADD COLUMN id integer GENERATED BY DEFAULT AS IDENTITY;
		ALTER TABLE products ADD PRIMARY KEY (id);

		-- Recreate dependent references as integer.
		ALTER TABLE IF EXISTS product_images DROP COLUMN IF EXISTS product_id;
		ALTER TABLE IF EXISTS product_images ADD COLUMN product_id integer;

		ALTER TABLE IF EXISTS inquiries DROP COLUMN IF EXISTS product_id;
		ALTER TABLE IF EXISTS inquiries ADD COLUMN product_id integer;

		ALTER TABLE IF EXISTS product_images
			ADD CONSTRAINT product_images_product_id_fkey
			FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;

		ALTER TABLE IF EXISTS inquiries
			ADD CONSTRAINT inquiries_product_id_fkey
			FOREIGN KEY (product_id) REFERENCES products(id);
	END IF;
END $$;
