-- Product table reset for Knits by Muna.
-- Run the full file in Supabase SQL Editor.
-- This recreates product-related tables in the public schema with matching integer IDs.

DROP TABLE IF EXISTS public.product_images CASCADE;
DROP TABLE IF EXISTS public.inquiries CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;

CREATE TABLE IF NOT EXISTS public.categories (
  id text PRIMARY KEY,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  image_url text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

CREATE TABLE public.products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL,
  price numeric(10, 2) NOT NULL,
  discounted_price numeric(10, 2),
  image_url text NOT NULL,
  category_id text REFERENCES public.categories(id),
  in_stock boolean NOT NULL DEFAULT true,
  is_featured boolean NOT NULL DEFAULT false,
  is_new_arrival boolean NOT NULL DEFAULT false,
  is_trending boolean NOT NULL DEFAULT false,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

CREATE TABLE public.product_images (
  id text PRIMARY KEY,
  product_id integer NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  image_url text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT now()
);

CREATE TABLE public.inquiries (
  id text PRIMARY KEY,
  customer_name text NOT NULL,
  customer_phone text,
  message text NOT NULL,
  product_id integer REFERENCES public.products(id),
  status text NOT NULL DEFAULT 'new',
  created_at timestamp NOT NULL DEFAULT now()
);

SELECT table_schema, table_name, column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public'
  AND (
    (table_name = 'products' AND column_name = 'id')
    OR (table_name = 'product_images' AND column_name = 'product_id')
    OR (table_name = 'inquiries' AND column_name = 'product_id')
  )
ORDER BY table_name, column_name;
